<a href="https://colab.research.google.com/github/mirzakazem/GraphTheory_MC_OR/blob/main/Markov_Chain___(Final_Exam_template).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

from numpy.linalg import matrix_power

from numpy import linalg as LA

In [ ]:
np.set_printoptions(precision=5,suppress=True)
#probability matrix


p=[[0,2/5,3/5,0.0],\
   [1/4,0.0,1/2,1/4],\
   [0.0,1/3,0.0,2/3],\
   [0,0.0,1,0.0]]
  

p=np.array(p)
print(p)

for i in range(len(p[1])):
    print("sum of proba for column",i,":" ,sum(p[i]))
    

[[0.      0.4     0.6     0.     ]
 [0.25    0.      0.5     0.25   ]
 [0.      0.33333 0.      0.66667]
 [0.      0.      1.      0.     ]]
sum of proba for column 0 : 1.0
sum of proba for column 1 : 1.0
sum of proba for column 2 : 1.0
sum of proba for column 3 : 1.0


In [ ]:
print("9-step transition between 4 and 4:",matrix_power(p,9)[3,3])

9-step transition between 4 and 4: 0.262716049382716


In [ ]:
#prove irreducibility
print(matrix_power(p,0)+matrix_power(p,1)+matrix_power(p,2)+matrix_power(p,3))



[[1.15    0.70667 1.46    0.68333]
 [0.31667 1.4     1.36667 0.91667]
 [0.08333 0.64444 1.96667 1.30556]
 [0.08333 0.33333 1.83333 1.75   ]]


In [ ]:
#prove irreducibility with loop
temp=matrix_power(p,0)
for i in range(1,4):
    temp+=matrix_power(p,i)
print(temp)

[[1.15    0.70667 1.46    0.68333]
 [0.31667 1.4     1.36667 0.91667]
 [0.08333 0.64444 1.96667 1.30556]
 [0.08333 0.33333 1.83333 1.75   ]]


In [ ]:
#compute the stationary PI of ergodic MC:
print("the stationary PI of ergodic MC:")
print("\n")
print(matrix_power(p,1000))

the stationary PI of ergodic MC:


[[0.04167 0.16667 0.45    0.34167]
 [0.04167 0.16667 0.45    0.34167]
 [0.04167 0.16667 0.45    0.34167]
 [0.04167 0.16667 0.45    0.34167]]


In [ ]:
#to get the average of processed waste per 1 hour:
p_stationary=matrix_power(p,1000)[1]
q=[0.5,1.5,2,2.5]
q=np.array(q)

e=p_stationary@np.matrix.transpose(q)
print(e,"tons")

2.0249999999999444 tons
